### ISSUE TITLE
Email input box jumps around whilst typing

### ISSUE THREAD

**Issue by BarnC** [andrewhathaway/Winterfell#1]
Hey up it's Barn, lib looks really good btw!

Just a minor UX thing I noticed when trying the demo, email box jumps up and down as my input goes from empty -> invalid -> valid.

I guess you may want to either display validation below, add a delay which resets on input, or add a validateOn option which would let me validate email on blur.

**Comment by andrewhathaway** [comment]
I've noticed this and I've been pondering the solution, the `validateOn` definitely sounds like a useful feature either way. Possibly a `errorPosition` option or something too.

Thanks for the issue, I'll get on it! :)

**Comment by MrRio** [comment]
Well designed forms that validate as-you-type will display errors in way that doesn't shift the input. 

Adding ``validateOn`` and ``errorPosition`` is probably extra cruft.

**Comment by andrewhathaway** [comment]
@MrRio Bearing in mind that Winterfell does not dictate the styling of the form, this is still completely possible. 

However, keeping in the flexible mindset. I think it might be worth implementing the `validateOn` feature and setting the default to `blur`.

**Comment by MrRio** [comment]
Yeah that'd do it.

It looks really awesome btw

**Comment by andrewhathaway** [comment]
I think its a good option from a flexibility point of view!

Appreciate it! :beers: soon.

**Comment by MrRio** [comment]
👍👍
