### ISSUE TITLE
Specify transform in package.json for browserify support

### ISSUE THREAD

**Issue by jwbrady** [andrewhathaway/Winterfell#11]
If you use the ["browserify.transform"](https://github.com/substack/node-browserify#browserifytransform) feature, it will make it easier for those who also use browserify at the app level to use your npm package. The two changes required to your package.json are: add a dependency on reactify (you currently only have a dev dependency), add at the below line.

```json
"browserify": { "transform": [ ["reactify",{"es6":true}] ] }
```

You may also wish to consider using [babelify](https://github.com/babel/babelify) instead. It is based on the babel project [which is replacing the react-tools project that reactify is based on](https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html). If you do, you can use this line instead (as well as a dependency on babelify):

```json
"browserify": { "transform": [ "babelify" ] }
```

**Comment by andrewhathaway** [comment]
Great idea. I shall update and commit in the morning. I thought I was using babelify, weird. I shall also switch that out too!

Thanks for the tip.

**Comment by jwbrady** [comment]
Turns out, by doing both #12 and #13, it now does extra unnecessary work. Since you targeted the precompiled code using `main` in package.json, browserify no longer needs babelify, but still applies it due to #12. I suggest removing the browserify.transform field in package.json.
