### ISSUE TITLE
Unable to build examples

### ISSUE THREAD

**Issue by Znow** [andrewhathaway/Winterfell#15]
Hi

I've tried for several time to get your example working.

I can see that there is a "gulp build-example"...

All though when I run this, I get the following:

```
[14:41:50] Starting 'build-examples'...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module 'react' from 'c:\Users\User\Downloads\Winterfell-master\Winterfell-master\examples'
```

Other than that, I have tried just to find a precompiled version of "Winterfell", to use with my app, but it seems I really have to build it....

Can you supply a production ready precompiled version of your plugin, ready to use?

Regards

**Comment by andrewhathaway** [comment]
Hi @Znow 

React does no longer ship as a dependancy of Winterfell any more, but a dev-dependancy. You must 

```javascript
npm install --dev
```

to install React alongisde it. 

As for the precompiled version of Winterfell, its in the `dist` folder and `require('winterfell')` will automatically require the precompiled version!

Hope that helps. :)
