### ISSUE TITLE
Additional simpler demo

### ISSUE THREAD

**Issue by anshumanf** [andrewhathaway/Winterfell#2]
First off - this looks real good and I am quite interested in using it in my personal projects.

Now - in addition to the existing demo, I think another with a smaller schema associated with it might help people get started up faster. The current demo is very useful but might work better as the second example.

Just my opinion. Good luck!

**Comment by andrewhathaway** [comment]
Hi there!

Thanks for the kind words! I definitely considered this, its quite hard to convey the workings of the schema without going all out. I'll put together a one page log in page as a simple demo, if that would be suitable!

Appreciated!

**Comment by andrewhathaway** [comment]
Fixed by 0190b933fc07781f8455949992bc325fcda384b2.

<3
