### ISSUE TITLE
textInput type throws error for emailInput

### ISSUE THREAD

**Issue by camerow** [andrewhathaway/Winterfell#25]
When using emailInput it defaulted to TextInput which threw an error from questions.js

**Comment by andrewhathaway** [comment]
Hi @camerow. 

Is this related to the pull request I just merged from you? Or is this unrelated, if so, can you supply some more detail please! 

Thanks.

**Comment by camerow** [comment]
It's related, sorry! Should've been more clear. Figured I'd make it an issue so people could potentially google-foo find it. =)
