### ISSUE TITLE
Support for front-end UI frameworks

### ISSUE THREAD

**Issue by abigtoe** [andrewhathaway/Winterfell#28]
Any thought about add a custom theming feature so one could slip in UI frameworks like Material-UI or even (god forbid) Bootstrap.  

I would mark this as a question, not issue, but I don't know how to do so

**Comment by andrewhathaway** [comment]
Hey @abigtoe.

Winterfell is built with the idea in mind that is flexible for your needs. You can add custom classes to types of elements around the instance of Winterfell, defined in the schema. 

You can find information regarding settings classes in the README. Fun fact, the Winterfell demo site uses Boostrap!

Thanks.
