### ISSUE TITLE
Access form element dom node

### ISSUE THREAD

**Issue by bbnnt** [andrewhathaway/Winterfell#31]
Well so far unsuccessful to get how to manipulate the form.
Let's say you'd want to hide/remove your form after a successful submit
I guess that's pretty simple; but my Winterfell.getDOMNode()'s object remains undefined wherever I check it

**Comment by andrewhathaway** [comment]
Hi there.

You should not be directly manipulating the form, Winterfell has customisations for things like that. 

You should not need to get the Winterfell DOMNode as you should already have a reference of what you render it in to. You could can then either remove the node or use `React. unmountComponentAtNode` to remove the component through React.

PS: You can only use `.getDOMNode` inside of a react component and by the ref of an element. However you are trying to call `.getDOMNode` on an un-rendered React component, not an instant of one etc.

**Comment by bbnnt** [comment]
Allright thanks, I'll look winterfell's customisations
