### ISSUE TITLE
Adding a title to a question set

### ISSUE THREAD

**Issue by bbnnt** [andrewhathaway/Winterfell#33]
I hope this dirty schema explains the idea :

![capture](https://41.media.tumblr.com/cde2774959de89565ccb20270082f760/tumblr_nvduzdphYD1qzp3szo1_540.jpg)

As there is a title to the panel, there'd be one on the set.
Or I missed the option in the docs

**Comment by andrewhathaway** [comment]
Hi @bbnnt.

You cannot currently add a title to a question set, but you can add one to a questionPanel and a question. If this is something you think would be worthwhile, it can be done!

**Comment by bbnnt** [comment]
Maybe the demo provided confused me; can you have all your panels displayed at the same time ?
That'd solve it too

**Comment by andrewhathaway** [comment]
Panels are not supposed to be displayed all at once no, panels are like pages. Question sets however are all rendered one after another.

**Comment by bbnnt** [comment]
That's what I wasn't sure of;
what do you think, worthwhile to add titles to questions sets ?

**Comment by andrewhathaway** [comment]
I imagine so If you wanting this and have a case for it.

Moving forward I can add it in sometime soon or you can PR it if you feel comfortable doing so!

**Comment by bbnnt** [comment]
I'd like to look into it; maybe you help point me where it might happen
Have to check the code a bit

**Comment by andrewhathaway** [comment]
@bbnnt Fixed. Information in the README. Will be live in the next release, which I am getting round to very soon.

**Comment by bbnnt** [comment]
could not get enough time to go into this;
but thanks a lot for this improvement !
