### ISSUE TITLE
Submit button

### ISSUE THREAD

**Issue by ryoia** [andrewhathaway/Winterfell#39]
Hi, I got rid of all submit button related things in this schema, but there is still a submit link on the page, does Winterfell internally generate the submit for all schemas?

http://pastebin.com/20gFktDS

Thanks!

**Comment by andrewhathaway** [comment]
A submit/next button is always shown, is there a reason you would want to disable the submit button?

**Comment by ryoia** [comment]
We have our own submit button that uses react-router's Link to another page, is there a way to do such thing in Winterfell? Thanks!

**Comment by andrewhathaway** [comment]
Out of curiosity, why would you want to do this? How would you submit the form if you are not having a submit action?

**Comment by ryoia** [comment]
We currently have two schemas, one is for login, then the main one. So the button we have has a link to the main page once the login credential passed.

**Comment by andrewhathaway** [comment]
Right I see. This feature would need to be implemented.

**Comment by ryoia** [comment]
That'd be good, thanks!

**Comment by andrewhathaway** [comment]
@ryoia Fixed. Will be pushed in the next update. Check the README for how I've implemented this.

**Comment by ryoia** [comment]
I see a button disabled option, I will try to set that to true. Thanks!

**Comment by andrewhathaway** [comment]
You will need to download the latest version from this repo and build it or wait for the new release.

**Comment by andrewhathaway** [comment]
@ryoia New version published.

**Comment by ryoia** [comment]
This worked as well, thank you for the quick release and fix!
