### ISSUE TITLE
hiddenInput value not set as expected

### ISSUE THREAD

**Issue by rowbare** [andrewhathaway/Winterfell#55]
hiddenInput sets the default props as follows:

HiddenInput.defaultProps = {
  name  : undefined,
  value : undefined
};

So this would appear to be the way to define a question for the hiddenInput
{
      "questionId" : "func",
      "question" : "",
      "input" : {
        "type" : "hiddenInput",
        "name" : "hiddenname",
        "value" : "hiddenvalue"
      }
}

However the value prop does not make it into the rendered <input> as this implies. Looking at the render method of question.js it appears as though moving the value property to the question might do what we want

    var value = typeof this.props.value !== 'undefined'
                  ? this.props.value
                  : typeof this.props.input.default !== 'undefined'
                      ? this.props.input.default
                      : undefined;

This definition did not work either since the value prop of the questions comes from the questionAnswers prop on the set and that seems like a pretty convoluted way to set a simple hidden input.
{
      "questionId" : "func",
      "question" : "",
      "input" : {
        "type" : "hiddenInput",
        "name" : "hiddenname",
      }
        "value" : "hiddenvalue"
} 

There is a simple but not obvious workaround by setting the default prop on the input:

{
      "questionId" : "func",
      "question" : "",
      "input" : {
        "type" : "hiddenInput",
        "name" : "hiddenname",
        "default" : "hiddenvalue"
      }
}

I am not sure if this should be seen as a documentation or a code issue.  Perhaps an additional level in the Question Render command might be the easiest solution:

    var value = typeof this.props.value !== 'undefined'
                  ? this.props.value
                  : typeof this.props.input.value!== 'undefined'
                      ? this.props.input.value
                      :  typeof this.props.input.default !== 'undefined'
                      ? this.props.input.default
                      : undefined;

**Comment by andrewhathaway** [comment]
Hi @rowbare.

The `input.value` value in the schema does not get passed through as the default value. In this case, an inputs `value` prop is the value set by the user. The `input.default` value in the schema however will be used until the used sets a value for an input.

Hope this clear things up. Thanks.
