### ISSUE TITLE
Multi page forms - async validations and routes

### ISSUE THREAD

**Issue by zanedev** [andrewhathaway/Winterfell#60]
With the built in multi-page forms functionality is there is a way to have async actions occur between steps (like server side validation - proceed to next step) and also any way to tie in routes to the steps?  I'd also like to send new data to the next step from the previous async action.

I'm trying to decide whether I should continue to use the built in Multi page form or have separate forms and wire in all the advanced step logic and routes myself.  I imagine this sort of logic would need to be tied to the schema so maybe it's just better to use separate forms for each step and not try to tackle this at a schema level.

**Comment by andrewhathaway** [comment]
Hi @zanedev. Just quickly reading over this, so apologies for the lack of a detailed response. However, I think the idea of using multiple forms would be a wise idea at a current stage, as for one Winterfell does not have support for async validations, and secondly I am unsure of how a JSON schema would handle firing requests and handling responses using a JSON schema. This would all have to be planned out, rather well.

I reckon using separate forms for now would be the best fit, and sadly you'll have to render your own error messages. Ideally, Winterfell would have the ```validationErrors``` prop passed from the root (index). So maybe you could alter Winterfell to do such a thing, then pass down your custom validation errors when using your async validation.

Apologies!

**Comment by zanedev** [comment]
No worries thanks for the response it helps a lot.  Hmm I like the benefits of the multi-form but I do agree it wouldn't fit in the schema easily so maybe I could look into simply hook into the prev/next functionality with the onSwitchPanel function.  I'll see what it takes and submit a PR if it's something worth doing.  Otherwise I'll continue with the single form approach.  Thanks again great framework!

**Comment by oscarnevarezleal** [comment]
Hi there, I just found this project. Since this is an old post I´d like to know if things have changed since its creation regarding async validations.
