### ISSUE TITLE
Display real time results into the form

### ISSUE THREAD

**Issue by funkyremi** [andrewhathaway/Winterfell#64]
Hi, I need to display result in real time according to values in the form.
What's the best way to do that?
Thank you again :-)

**Comment by andrewhathaway** [comment]
What exactly do you mean by realtime result? Give me an example which would include the actions you would want to complete.

**Comment by funkyremi** [comment]
Like two fields, one with a quantity, one with the price. When I enter both informations, the result would be displayed just under the fields without submitting the form.

**Comment by andrewhathaway** [comment]
To me this sounds like it is out of Winterfell's scope. This would require a different programatical aspect to the forms, but at the moment they're just JSON. Therefore we can not action anything like this. Apologies!
