### ISSUE TITLE
Add/remove fields dynamicaly

### ISSUE THREAD

**Issue by funkyremi** [andrewhathaway/Winterfell#65]
Is there a way to create fields that can be added or removed dynamically?
Example: A group field to enter an invoice line (product and price) and a '+' button to add a new invoice line. A '-' button to remove the new added line.
Thank you Andrew for the great work with Winterfell!

**Comment by andrewhathaway** [comment]
This falls under #4. As of yet, there is now way to do this, however plans are underway.
