### ISSUE TITLE
Reset form on submit

### ISSUE THREAD

**Issue by elaine0304** [andrewhathaway/Winterfell#67]
Is there a way to reset the form once it is submitted?

After I submit a form, I'm redirecting to another page. But, once I go to the form again, all the values previously typed in/selected(in case of radio buttons) are already present. I need the values to be cleared from the form.

Edit : I believe what I basically need is to refresh the questionAnswers object.

**Comment by andrewhathaway** [comment]
Hey @elaine0304, at the moment there is no direct reset call, however yes you can pass in the `questionAnswers` object, and keep track using the `onUpdate` handler. Another option is to ensure that Winterfell gets unmounted and remounted as a new component. This might be wise as the former option could cause issues when using multiple panels etc. Hope that clears it up!

**Comment by elaine0304** [comment]
Thank you so much for your response.

Is there a specific way to ensure that Winterfell gets unmounted and remounted as a new component?

**Comment by andrewhathaway** [comment]
Hi @elaine0304, no worries! 

One way you could do this is have a wrapper component that renders Winterfell. This component will have some boolean `prop` on it, which you can use to choose to render Winterfell or not, named `visible` or something similar.

In the higher components render function, you can do something like:

```javascript
render()
{
  return (
    <div>
      {this.props.visible
        ? <Winterfell {...props} />
        : undefined}
    </div>
  );
}
```

Then when the Winterfell form has been submitted, you can set `visible` to false, and when you set it back to `true` the component will remount, and will be reset completely.

Hope this makes sense!
