### ISSUE TITLE
Warning: EmailInput is changing an uncontrolled input of type email to be controlled.

### ISSUE THREAD

**Issue by JD2k** [andrewhathaway/Winterfell#69]
Hello,

i am getting this answer when entering an email in the example form (My Awesome Form). Can you help me here?

Thanks in advance

**Comment by andrewhathaway** [comment]
Hi @JD2k this issue should be resolved in the next release. I'll get to this now.

**Comment by andrewhathaway** [comment]
@JD2k Released in 1.1.1.
