### ISSUE TITLE
Multi-field validation

### ISSUE THREAD

**Issue by keisans** [andrewhathaway/Winterfell#7]
When validating a form, it would be convenient if there were a way to validate against multiple different fields. An example might be a date-range input with a start date and an end date. The form would be invalid if the end date came before the start date, even though both fields might be valid independently.

**Comment by andrewhathaway** [comment]
Great idea.

First part of adding this feature is to think of the suitable schema format for this.

Any suggestions off the bat? I'll try to think of something meanwhile!

**Comment by andrewhathaway** [comment]
Hi @keisans! Also @VinSpee

I've been thinking about this, and we'd need a way of distinguishing between a normal value and a `questionId` (to get its answer). Whilst it needs to be simple, it also needs to be nice.

I've been thinking, and how would you guys feel about variations or some of the following:

```
{questionId}
${questionId}
:questionId
$questionId
```

Using these characters, we could decide whether its a questions-value we need to pull, or just a normal value.

Any other suggestions would be great!

**Comment by andrewhathaway** [comment]
Master now has this, check the README for details. Will push a new version soon to npm.
