### ISSUE TITLE
Include a non-minified version of Winterfell.

### ISSUE THREAD

**Issue by christopher-wilson** [andrewhathaway/Winterfell#73]
Maybe I am missing something, but there doesn't seem to be an unminified copy of winterfell. I'm not sure if you mean for us to build it if we want it, but many libraries include both versions of code.

**Comment by andrewhathaway** [comment]
Hi @christopher-wilson.

Inside the `dist` folder, you will see a build and unminified version of the Winterfell project. You can require it from the `index.js` file inside `dist`.

Thanks.
