### ISSUE TITLE
A Way to get all choices?

### ISSUE THREAD

**Issue by christopher-wilson** [andrewhathaway/Winterfell#74]
Being based on React, there could be a way to retrieve the choices as a single parsible object. I don't know if this would require using one of the data store libraries, or just creating an object with nested data.

It would be incredibly useful to have something, either way.

**Comment by andrewhathaway** [comment]
Hi @christopher-wilson. Apologies for the late response, this must have slipped away. Which "choices" are you speaking of exactly? More information would be helpful! Thanks.

**Comment by christopher-wilson** [comment]
It would be nice to have a way to return all the options in an object. Say you build a form, and you submit, it would be great to generate an object with all the data we selected. Parsing the data was difficult last time I looked. 

Maybe if there were an object that data was stored to as we went through our forms, like a root data object that you see in React or Vue sometimes.

**Comment by andrewhathaway** [comment]
@christopher-wilson If you're talking about the results from the form, the [events section](https://github.com/andrewhathaway/Winterfell#events) of the README includes information with passing callbacks when a question is answered or the entire form is submitted. Each one returns the object containing the users answers.

Hope this helps!
