### ISSUE TITLE
State leaks into prototype

### ISSUE THREAD

**Issue by Teelevision** [andrewhathaway/Winterfell#76]
When displaying two forms, I would expect both to be separated. Instead it seems that the state is shared.

**How to reproduce**
Insert two forms with the same schema into your page. Fill out the first and submit the second without any inputs. The second form will submit the inputs of the first form.

**Possible solutions**
I suspect that this is due to the way how default values are taken into the state. The constructor of the `Winterfell` class does this:
```js
this.state = {
      schema          : schema,
      currentPanel    : currentPanel,
      action          : this.props.action,
      questionAnswers : this.props.questionAnswers
};
```
When initializing the form, the `Winterfell.defaultProps` are passed into the constructor. After the code above `this.state.questionAnswers` is the same object as `Winterfell.defaultProps.questionAnswers`. Every change to this state also causes the prototype to change. Every form, even if displayed one after another, shares the same `questionAnswers`.
Generating the default properties within the constructor instead of holding them statically on the class could help.

**Possible workaround**
Passing the `questionAnswers` as a property while holding them in the state of the surrounding component. And listening to any updates.

**Comment by andrewhathaway** [comment]
Hi @Teelevision, apologies for the delayed reply.

Thanks for pointing this out, I'm going to quickly try repo and see if I can sort out a fix. Will update as I go along.

**Comment by andrewhathaway** [comment]
Put a fix in a branch for now and it does the trick. Will look in to some more stuff and bump the version, and release when I can. :) Thanks!
