### ISSUE TITLE
[Question] Is it possible to have "infinite" fields

### ISSUE THREAD

**Issue by mikaoelitiana** [andrewhathaway/Winterfell#80]
I am looking for a "infinite" field feature, ie the user can add multiple values for a field or set of fields. 
Say I want to create a list of todos and I would have a "+" button to add display more fields and input more todo.
Is there currently a way to do that? If not would that be in the roadmap (I am willing to help )?

Thanks

**Comment by andrewhathaway** [comment]
Hi @mikaoelitiana!

This has been spoken about and has been in the backlog for a while, #4. If you fancy having a go, I'd definitely be up for reviewing a PR!

Thanks.

**Comment by andrewhathaway** [comment]
Closing due to dupe.
