### ISSUE TITLE
questionAnswers filtered by question paths onSubmit

### ISSUE THREAD

**Issue by geekyme** [andrewhathaway/Winterfell#85]
## Current behavior

In the demo, http://winterfell.andrewhathaway.net/, I first executed the path of an unsubscribed user. Therefore creating a json payload below:

<img width="354" alt="screen shot 2017-03-18 at 8 31 08 pm" src="https://cloud.githubusercontent.com/assets/977460/24072000/df5aac06-0c19-11e7-9051-ff6f30b58c0d.png">

After that, I click back and executed the path of a subscribed user. And I see the json payload below:

<img width="386" alt="screen shot 2017-03-18 at 8 32 11 pm" src="https://cloud.githubusercontent.com/assets/977460/24072008/00217640-0c1a-11e7-998b-4954756b61aa.png">

## Expected behavior

The printed json payload should only contain data relevant to executed path. ie. I should not see any of the `reg-*` fields.

**Comment by andrewhathaway** [comment]
Hi @geekyme, yes you are correct. This, sadly, has been in from the start. I'll have to spend some time looking in to the issues for this project, PRs are accepted too!

**Comment by andrewhathaway** [comment]
Closing due to dupe (#5).
