### ISSUE TITLE
Required asterisk for required fields. 

### ISSUE THREAD

**Issue by andrewhathaway** [andrewhathaway/Winterfell#9]
Render an asterisk for fields that contain a new `required` property on a `question` object. Support a custom class. Possibly a custom render handler?

**Comment by VinSpee** [comment]
I think it would be the most flexible to allow a custom class for a field marked "required" or "optional". That way the label or input can be styled with a pseudoclass like:

```css
.is-optional:after {
  content: '*';
}
```

**Comment by andrewhathaway** [comment]
That's fine, but I imagine some people may want to use an actual element instead of pseudo elements?

**Comment by VinSpee** [comment]
Actually maybe we should follow the HTML spec here and key off the the `required` attribute?

**Comment by andrewhathaway** [comment]
@VinSpee Do you mean, use the required attribute on inputs? We would still need to show an asterisk on labels, which is obviously fine?

**Comment by VinSpee** [comment]
Ahh good point. I'd prefer to keep it flexible if possible - maybe a custom element is the most flexible way to go. 



(null)

**Comment by andrewhathaway** [comment]
So to round up, what do you think the outcome should be?

Required field on a question results in the required attribute on an input, as well as an element for the asterisk?

**Comment by VinSpee** [comment]
I'd say keep the element optional, allowing people to style with css if they want or use the custom element if they want. Make sense?

**Comment by andrewhathaway** [comment]
I reckon:

* `required` field will add the required attribute on an input.
* If there is a `required` class set and the `required` attribute is set, that shall be placed on the question wrapper
* Possibly an option somewhere to add an element for the asterisk?
