### ISSUE TITLE
Uncaught TypeError: this.props.onRender is not a function

### ISSUE THREAD

**Issue by tmcdonnell87** [andrewhathaway/Winterfell#90]
Sorry if I'm missing something basic here. I love the idea of using this for my next project, but the boilerplate is throwing an error: `Uncaught TypeError: this.props.onRender is not a function`

Furthermore, when I change anything, I get `Uncaught TypeError: Cannot read property 'bind' of undefined`.

Problem is reproduced here: https://esnextb.in/?gist=07a8b8d62af04bb39693f8bae5344a8b. (Open the console to see the errors.)

**Comment by andrewhathaway** [comment]
Oh wow, this is interesting. I haven't seen this yet. I'll investigate at some point this weekend. Feel free to dig in to the code and submit a PR!

**Comment by andrewhathaway** [comment]
@tmcdonnell87 I've managed to reproduce and push a fix, however I'll need to publish a new version.

**Comment by tmcdonnell87** [comment]
Thanks for the quick response, @andrewhathaway. Upgrading to 1.1.2 did not fix the problem. (As far as I can tell, #848a5113b54d5764b2c9addf1c56ac689d7eccc6 only changed the readme and version number?

**Comment by andrewhathaway** [comment]
Oh damn, I must have messed something up. Let me see where my code went! :p

**Comment by andrewhathaway** [comment]
Hi @tmcdonnell87 I've pushed a quick fix. That should fix it, however I think I'll be attempting to move forward with a 2.0 when I can find the time to fix issues like this, add tests, modernise the project and also add new features.
