### ISSUE TITLE
Page reload on submit

### ISSUE THREAD

**Issue by waheed25** [andrewhathaway/Winterfell#92]
when i press submit button it didn't console anything in the submit function and page reloads and fields are reset while page reload. here is my little code of schema

 "questionPanels" : [{
        "panelId" : "register-panel",
        "panelHeader" : "Log in ",
        "panelText" : " enter your email address and password to log in.",
        "action" : {
            "default" : {
                "action" : "SUBMIT"
            }
        },

**Comment by andrewhathaway** [comment]
Hi there @waheed25!

I suggest reading the documentation in the README, as it explains all you'll need right there! To disable natural form submission, you can use the `disableSubmit` prop.

More info here: https://github.com/andrewhathaway/Winterfell#props--config

Thanks!

**Comment by waheed25** [comment]
yup ....sorry my bad..... problem solved
