### ISSUE TITLE
TypeError: this.props.onRender is not a function

### ISSUE THREAD

**Issue by Walteristic** [andrewhathaway/Winterfell#95]
Hi Andrew,

I have encounter this issue 'this.props.onRender is not a function' while using Winterfell. 
![winterfell_issue1](https://user-images.githubusercontent.com/30488435/28655280-4898ec2c-72cd-11e7-8da4-f4a72ddf1fdc.jpg)

However, the form works fine after I closed the console report. Is there a bug I should be concerned about? Or it is safe to ignore?  
![winterfell_issue2](https://user-images.githubusercontent.com/30488435/28655320-9940a6c4-72cd-11e7-9f4d-64adc7c6ca0b.jpg)

Thanks.

Cheers,
Walteristic.

**Comment by andrewhathaway** [comment]
Hi @Walteristic!

It has become apparent that Winterfell now requires all of the event props, even if they're empty functions, for some reason. I'll be looking in to this shortly, but for now you should be able to pass the `onRender`, `onUpdate`, `onSubmit` and `onSwitchPanel` props to prevent these errors.

Thanks!
