### ISSUE TITLE
Running examples

### ISSUE THREAD

**Issue by tedstrauss** [andrewhathaway/Winterfell#96]
I have installed this project, and run `gulp build-examples` and  `gulp watch-examples`.

Can anyone tell me how I start serving the app to the web? Or which port it would be visible on? Do i need to make some kind of wrapper first?

Sorry, nodejs noob

**Comment by andrewhathaway** [comment]
You should be able to just open up the examples/index.html file and should all work! Thanks! :)

**Comment by tedstrauss** [comment]
open up where? what does that mean?

**Comment by andrewhathaway** [comment]
In your browser

**Comment by tedstrauss** [comment]
CURL and browser are not loading any pages at http://127.0.0.1/examples/   
`Connection refused`

**Comment by andrewhathaway** [comment]
You shouldn't need to use a server to open the file, just open the index.html file in your browser.
